name: Complete User Mapping Workflow

on:
  workflow_dispatch:

jobs:
  migrate:
    name: Migrate User Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate User Mappings File
        run: |
          mkdir -p ./template
          echo "mannequin-user,mannequin-id,target-user" > ./template/user-mappings-template.csv
          echo "vaidy-ea,M_kgDOCvo_Fw," >> ./template/user-mappings-template.csv
          echo "JayashreeMGM,M_kgDOCvoBaw," >> ./template/user-mappings-template.csv

      - name: Upload User Mappings Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-mappings-template
          path: ./template/user-mappings-template.csv

  trigger-user-mapping-workflow:
    name: Trigger User Mapping Migration
    runs-on: ubuntu-latest
    needs: migrate  # Ensure it runs after migration completes

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download user mapping file artifact
        uses: actions/download-artifact@v3
        with:
          name: user-mappings-template
          path: ./artifacts

      - name: List downloaded files
        run: ls -R ./artifacts

      - name: Trigger Workflow 2
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.MY_PAT }}
          event-type: user-mapping-migration
          client-payload: '{"USER_MAPPINGS_FILE": "./artifacts/user-mappings-template.csv"}'
