name: Commit History Mapping Workflow

on:
  workflow_dispatch:

permissions:
  contents: write
  actions: write

jobs:
  # Step 1: Prepare Job
  prepare:
    runs-on: ubuntu-latest

    outputs:
      repo_name: "mannequin"
      repo_org: "Skanchi09"
      target_org: "Skanchi09"

    steps:
      - name: Set Outputs
        run: |
          echo "repo_name=mannequin" >> $GITHUB_ENV
          echo "repo_org=Skanchi09" >> $GITHUB_ENV
          echo "target_org=Skanchi09" >> $GITHUB_ENV

  # Step 2: Migrate Job
  migrate:
    runs-on: ubuntu-latest
    needs: [prepare]

    outputs:
      repo_name: ${{ needs.prepare.outputs.repo_name }}
      repo_org: ${{ needs.prepare.outputs.repo_org }}
      target_org: ${{ needs.prepare.outputs.target_org }}

    steps:
      - name: Print Variables
        run: |
          echo "Repository Name: ${{ needs.prepare.outputs.repo_name }}"
          echo "Repository Org: ${{ needs.prepare.outputs.repo_org }}"
          echo "Target Org: ${{ needs.prepare.outputs.target_org }}"

      - name: Validate Migration Readiness
        run: echo "Migration Validation Complete!"

  # Step 3: Commit History Mapping Job
  Commit-history-mapping:
    runs-on: ubuntu-latest
    needs: [prepare, migrate]

    steps:
      - name: Print Variables
        run: |
          echo "Repository Name: ${{ needs.migrate.outputs.repo_name }}"
          echo "Repository Org: ${{ needs.migrate.outputs.repo_org }}"
          echo "Target Org: ${{ needs.migrate.outputs.target_org }}"

      - name: Trigger Commit-history-mapping in Target
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.MY_TOKEN }}
          event-type: Commit-history-mapping-updated
          client-payload: |
            {
              "repo_name": "${{ needs.migrate.outputs.repo_name }}",
              "repo_org": "${{ needs.migrate.outputs.repo_org }}",
              "target_org": "${{ needs.migrate.outputs.target_org }}"
            }

      - name: Wait for Triggered Workflow to Start
        id: wait
        run: |
          echo "Checking for the triggered workflow to start..."
          sleep 10

      - name: Monitor Triggered Workflow
        id: monitor
        uses: actions/github-script@v6
        with:
          script: |
            const fetch = require('node-fetch');

            // Define the parameters
            const repo = process.env.GITHUB_REPOSITORY;
            const workflowRunUrl = `https://api.github.com/repos/${repo}/actions/runs`;
            const token = process.env.GITHUB_TOKEN;

            // Fetch the latest workflow run
            const response = await fetch(`${workflowRunUrl}`, {
              headers: { Authorization: `Bearer ${token}` },
            });
            const runs = await response.json();

            // Get the workflow run for the triggered event
            const triggeredRun = runs.workflow_runs.find(
              (run) =>
                run.event === "repository_dispatch" &&
                run.status !== "completed"
            );

            if (!triggeredRun) {
              core.setFailed("Triggered workflow did not start or was not found.");
            } else {
              console.log(`Triggered Workflow URL: ${triggeredRun.html_url}`);
              core.setOutput("run_id", triggeredRun.id);
              core.setOutput("run_status", triggeredRun.status);
            }

      - name: Monitor Workflow Status
        run: |
          RUN_ID=${{ steps.monitor.outputs.run_id }}
          while true; do
            STATUS=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID --jq .status --silent)
            echo "Current Status: $STATUS"
            if [[ "$STATUS" == "completed" ]]; then
              CONCLUSION=$(gh api repos/${{ github.repository }}/actions/runs/$RUN_ID --jq .conclusion --silent)
              echo "Workflow Completed with Conclusion: $CONCLUSION"
              if [[ "$CONCLUSION" == "success" ]]; then
                exit 0
              else
                echo "Triggered workflow failed!"
                exit 1
              fi
            fi
            sleep 10
          done
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Proceed to Next Job
        run: echo "Triggered workflow succeeded. Proceeding to the next steps!"

  # Optional: Notification Job
  notify:
    runs-on: ubuntu-latest
    needs: [Commit-history-mapping]

    steps:
      - name: Notify Completion
        run: echo "Commit History Mapping Workflow Completed!"


