name: User Mapping Migration Workflow

on:
  workflow_dispatch:

jobs:
  run-migration-script:
    runs-on: ubuntu-latest

    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      EMU_USERS_FILE: ./'MGM Resorts GitHub Enterprise Users - 11-06-24.xlsx'
      USER_MAPPINGS_FILE: ./user-mappings-template.csv
      ORG_NAME: ${{ secrets.ORG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dotenv openpyxl

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      - name: Authenticate GitHub CLI
        run: echo "${{ secrets.GITHUB_TOKEN }}" | gh auth login --with-token

      - name: Run migration script
        run: python ./migration_script.py

      - name: Post-execution status
        if: always()
        run: echo "Workflow execution completed."
