name: Complete User Mapping Workflow

on:
  workflow_dispatch:

jobs:
  migrate:
    name: Migrate User Data
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Generate User Mappings File
        run: |
          mkdir -p ./template
          echo "mannequin-user,mannequin-id,target-user" > ./template/user-mappings-template.csv
          echo "vaidy-ea,M_kgDOCvo_Fw," >> ./template/user-mappings-template.csv
          echo "JayashreeMGM,M_kgDOCvoBaw," >> ./template/user-mappings-template.csv

      - name: Upload User Mappings Artifact
        uses: actions/upload-artifact@v3
        with:
          name: user-mappings-template
          path: ./template/user-mappings-template.csv

  process-user-mapping:
    name: Process User Mapping
    runs-on: ubuntu-latest
    needs: migrate

    env:
      GH_PAT: ${{ secrets.GH_PAT }}
      EMU_USERS_FILE: ./authors.xlsx
      USER_MAPPINGS_FILE: ./artifacts/user-mappings-template.csv
      ORG_NAME: ${{ secrets.ORG_NAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download user mapping file artifact
        uses: actions/download-artifact@v3
        with:
          name: user-mappings-template
          path: ./artifacts

      - name: Debug File System
        run: ls -R ./artifacts

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas python-dotenv openpyxl

      - name: Install GitHub CLI
        run: |
          sudo apt-get update
          sudo apt-get install -y gh

      # - name: Authenticate GitHub CLI
      #   run: echo "${{ secrets.GH_PAT }}" | gh auth login --with-token

      - name: Install GitHub Enterprise Importer Extension
        run: |
          gh extension install github/gh-gei
        env:
          GH_TOKEN: ${{ github.token }}

      - name: Run migration script
        run: python ./.github/scripts/mapping.py

      - name: Post-execution status
        if: always()
        run: echo "Workflow execution completed."
